### PR TITLE
Adding CWL 

### PR DESCRIPTION
**Pull request by Jeltje**
This PR adds CWL for radia.py and radia_filter.py and puts both scripts on the radia-tool docker container

Other changes:
- Changed `%default by default` in option help strings (it doesn't work) to the actual default values of each parameter
- Removed the `<nnn>UseChr` parameter as it was set during the `radia.py` run (it didn't work as expected)
- Set some docker specific defaults for script locations
- Changed the default output of `radia_filter.py` to `filtered_out.vcf` to distinguish from radia's `out.vcf`.

### CODE REVIEW

**Comment by kellrott** [comment]
There was a downstream filter that had to be put in place because radia was passing germline calls downstream: https://github.com/covingto/pancanmafmerge/blob/master/filter_radia.py

Does this patch touch any of that logic?

**Comment by Jeltje** [comment]
@kellrott The downstream filter can be applied as before - would you like me to incorporate it into the filter_radia wrapper directly?

**Comment by kellrott** [comment]
I think having it in radia_filter.py is appropriate. Those are germline calls that were supposed to be removed, the downstream filter was a 'hack' to fix a problem with the outputs, but it only fixes the MAF file. Ideally, the VCFs would be correct as well.

**Comment by Jeltje** [comment]
Will do & create a new pr

**Comment by Jeltje** [comment]
The logic was already part of radia_filter.py, there's a `--filter-germline` option that removes the SS=1 calls. This option is set to True by default in the radia_filter.cwl.yaml.

I have confirmed that these settings match the results of `pancanmafmerge/filter_radia.py`

Reopening PR

**Pull request merged**
